### ISSUE TITLE
Questions: empty strings | required => 0 post-check

### ISSUE THREAD

**Issue by renatocron** [gphat/data-verifier#9]
Hello.

What is the reasons for empty strings means undef ? 

Sometimes I want to use required=>0 with post_check for verify if empty-string is a valid value, and undef is not.

**Comment by renatocron** [comment]
@gphat are you still there?

**Comment by gphat** [comment]
Hey @renatocron,

I don't see any difference between undef and an empty string. Many implementations of a form, when submitted, will return an empty string for the value. As far as I know, there's no way to differentiate between an intentionally empty field and a field with an undef.

Are you perhaps using this module in a non HTTP form sort of way?
